#index:
#    path: /
#    controller: App\Controller\DefaultController::index

foo:
    resource: routes/foo.yaml
    prefix: /
    defaults:
        _format: html
    host:
        en: 'foo.loc'
        pl: 'pl.foo.loc'
